### ISSUE TITLE
kernel crash: "attempted to kill init" on qemu-system-arm 2.5.0

### ISSUE THREAD

**Issue by bphermansson** [nachoparker/qemu-raspbian-network#6] opened 2017-04-27 08:30 UTC
I try to use the script on Linux Mint. The Raspbian system crashes at boot, think it's because sda2 cant be mounted. See attached screenshot.
![skarmbild fran 2017-04-27 10-26-46](https://cloud.githubusercontent.com/assets/3775861/25474690/6098a56e-2b34-11e7-98bd-181040013537.png)

**Comment by nachoparker** [comment] 2017-04-27 17:52
what version of `qemu-pi.sh` are you using? seems to me as a duplicate of #5

**Comment by nachoparker** [comment] 2017-04-27 17:55
also, what version of `qemu-system-arm` are you using?

**Comment by bphermansson** [comment] 2017-04-28 06:51
2.5... Not good I see :)
I'll try to upgrade qemu-system-arm and try again.

**Comment by nachoparker** [comment] 2017-04-28 07:06
well, 2.5 should also work. @kaiwan just tested it on Ubuntu.

Pull the latest code, you should not need to upgrade

**Comment by bphermansson** [comment] 2017-05-09 04:53
Ok I tested now on Kde Neon, it crashes. 
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.11), Copyright (c) 2003-2008 Fabrice Bellard

**Comment by bphermansson** [comment] 2017-05-11 07:09
Ok I tested now on Kde Neon, it crashes. 
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.11), Copyright (c) 2003-2008 Fabrice Bellard

**Comment by nachoparker** [comment] 2017-05-17 19:12
can you mount the boot partition (after it crashes) and see if the file `/etc/ld.so.preload` has the line that contains `libarmmem.so` commented out?

**Comment by bphermansson** [comment] 2017-05-25 03:51
No it dont, it's just like this:

/usr/lib/arm-linux-gnueabihf/libarmmem.so

**Comment by nachoparker** [comment] 2017-05-25 14:06
I think I fixed the error. Please, pull the latest code and try again.

**Closed as completed by nachoparker** 2017-05-25 14:06 UTC
Labels: duplicate

**Comment by bphermansson** [comment] 2017-06-01 13:31
Ok fine, it works now. Good job!
